apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec:
      containers:
      - image: fastapi:v0.1
        name: fastapi
        resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: backend
